#ifndef ASSETS_CHARACTER_BLOCK_H
#define ASSETS_CHARACTER_BLOCK_H

#include "ultra64.h"
#include "alignment.h"

#include "unknown_defines.h"

#define CHARACTER_BLOCK_1_WIDTH  (64)
#define CHARACTER_BLOCK_1_HEIGHT (32)

#define CHARACTER_BLOCK_2_WIDTH  (64)
#define CHARACTER_BLOCK_2_HEIGHT (32)

#define CHARACTER_BLOCK_3_WIDTH  (64)
#define CHARACTER_BLOCK_3_HEIGHT (16)

#define CHARACTER_BLOCK_4_WIDTH  (64)
#define CHARACTER_BLOCK_4_HEIGHT (16)

#define CHARACTER_BLOCK_TLUT_SIZE (0x100)

#define CHARACTER_BLOCK_5_WIDTH  (64)
#define CHARACTER_BLOCK_5_HEIGHT (32)

typedef struct CharacterBlockTextures {
    /* 0x0000 */ u8 unk_0000[CHARACTER_BLOCK_1_WIDTH * CHARACTER_BLOCK_1_HEIGHT];
    /* 0x0800 */ u8 unk_0800[B_801F9D00_USA_LEN][CHARACTER_BLOCK_2_WIDTH * CHARACTER_BLOCK_2_HEIGHT];
    /* 0x3800 */ u8 unk_3800[CHARACTER_BLOCK_3_WIDTH * CHARACTER_BLOCK_3_HEIGHT];
    /* 0x3C00 */ u8 unk_3C00[CHARACTER_BLOCK_4_WIDTH * CHARACTER_BLOCK_4_HEIGHT];
    /* 0x4000 */ u16 unk_4000[CHARACTER_BLOCK_TLUT_SIZE];
    /* 0x4200 */ u16 unk_4200[BRICKTXTR_LEN][CHARACTER_BLOCK_5_WIDTH * CHARACTER_BLOCK_5_HEIGHT];
} CharacterBlockTextures ALIGNED(8);

#endif
