#ifndef ASSETS_SIGN_PAUSE_H
#define ASSETS_SIGN_PAUSE_H

#include "ultra64.h"

#define SIGNPAUSE_PAUSE_WIDTH 64
#define SIGNPAUSE_PAUSE_HEIGHT 24

#define SIGNPAUSE_POPUP_WIDTH 128

#if VERSION_GER
#define SIGNPAUSE_POPUP_CONTINUE_HEIGHT 63
#define SIGNPAUSE_POPUP_CONTINUE_RESTART_HEIGHT 77
#else
#define SIGNPAUSE_POPUP_CONTINUE_HEIGHT 46
#define SIGNPAUSE_POPUP_CONTINUE_RESTART_HEIGHT 61
#endif

#define SIGNPAUSE_POPUP_PALETTE_SIZE 0x100

typedef struct SignPauseTextures {
    /* 0x0000 */ u32 pause[SIGNPAUSE_PAUSE_WIDTH * SIGNPAUSE_PAUSE_HEIGHT];
    /* 0x1800 */ u8 popup_continue[SIGNPAUSE_POPUP_WIDTH * SIGNPAUSE_POPUP_CONTINUE_HEIGHT];
    /* 0x2F00 */ u8 popup_continue_restart[SIGNPAUSE_POPUP_WIDTH * SIGNPAUSE_POPUP_CONTINUE_RESTART_HEIGHT];
    /* 0x4D80 */ u16 popup_palette[SIGNPAUSE_POPUP_PALETTE_SIZE];
} SignPauseTextures; // size = 0x4F80

#endif
