compiler_type = "gcc"

[preserve_macros]
NULL = "int"
"g[DS]P.*" = "void"
"gs[DS]P.*" = "void"
"gDma.*" = "void"
"G_IM_SIZ_.*" = "int"
"G_[AC]C.*" = "int"

[decompme.compilers]
"COMPILER_PATH=tools/gcc_kmc/linux/2.7.2" = "gcc2.7.2kmc"
