segments:
  - type: group
    start: 0x0
    dir: assets_074280/581DF0
    subsegments:
      - { start: 0x18, type: rgba16, name: tex0.rgba16, width: 112, height: 155 }
      - { start: auto, type: rgba16, name: tex1.rgba16, width:  88, height:  72 }
  - [0x00B940]

options:
  basename: ""
  base_path: ../../../../../
  compiler: GCC
  find_file_boundaries: False
  platform: n64
  extensions_path: tools/splat_ext

  do_c_func_detection: False
  o_as_suffix: True
  gfx_ucode: f3dex
  use_legacy_include_asm: False
  create_undefined_funcs_auto: False
  create_undefined_syms_auto: False
