name: Check format

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  build:
    name: Check format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v3

    - name: Install package requirements
      run: sudo apt-get install -y make git build-essential clang binutils-mips-linux-gnu gcc-mips-linux-gnu python3 python3-pip clang-format-11 clang-tidy-11

    - name: Check format
      run: ./tools/check_format.sh
